### ISSUE TITLE
pcr-branch-table.py Runtime Error IDA Pro 7.2

### ISSUE THREAD

**Issue by paulmcquad** [zznop/ida-genesis#2]
undefined function __loaders__pcr-branch-table.accept_file

**Comment by zznop** [comment]
Looks like you put pcr-branch-table.py in your loaders directory. pcr-branch-table.py is a different IDA script, not a loader. Only sg_smd.py should be placed in your loaders directory (per the README)

**Comment by zznop** [comment]
Also, I don't know if these scripts will work with IDA 7.2. They are written in Python 3, which I think was added in 7.4?
